export const SUBSCRIPTION_PLANS = [
  {
    name: "Free",
    tier: "Free",
    subtitle: "PERSONAL USE",
    price: "0DA",
    priceSub: null,
    priceBelow: "/MO",
    features: [
      "Basic shipping features",
      "Low-priority delivery",
      "3 active shipment posts",
    ],
    buttonText: "Current Plan",
    buttonVariant: "current",
    recommended: false,
    isBusiness: false,
  },
  {
    name: "Individual",
    tier: "Individual",
    subtitle: "REGULAR SHIPPERS",
    price: "3000DA",
    priceSub: null,
    priceBelow: "/MO",
    features: [
      "Real-time tracking",
      "Priority support 24/7",
      "Unlimited shipment posts",
      "Advanced route analytics",
    ],
    buttonText: "Select Plan",
    buttonVariant: "select",
    recommended: true,
    isBusiness: false,
  },
  {
    name: "Business",
    tier: "Business",
    subtitle: "LOGISTICS MODELS",
    price: "10000DA",
    priceSub: null,
    priceBelow: "/MO",
    features: [
      "Fleet management suite",
      "Bulk shipment tools",
      "Enterprise API access",
      "Dedicated account manager",
    ],
    buttonText: "Upgrade to Business",
    buttonVariant: "upgrade",
    recommended: false,
    isBusiness: true,
  },
];
